### ISSUE TITLE
maxlength prefix is too short.

### ISSUE THREAD

**Issue by Thor-cb90** [PieterL75/netbox_ipcalculator#13]
Hi,
the maxlegth is too short

for example, if i put in the ip 192.168.255.0, i can't choose a subnet smaller than /9 because of this:
![image](https://github.com/PieterL75/netbox_ipcalculator/assets/131167068/95e38b2f-45c6-48a2-a6e3-80429636d2c2)
here's the code in the dev-console:
![image](https://github.com/PieterL75/netbox_ipcalculator/assets/131167068/efd1fe31-3360-48e0-9642-36f691258345)
If i change the maxlength="15" to maxlength="16" it works..

**Comment by PieterL75** [comment]
There is actually no reason at all to have a maxlength or size overthere...
It's part of the code I used from DavidC.

I'll remove it and release an update

**Comment by PieterL75** [comment]
I release v1.4.4.

Thx for reporting and providing the fix !
