### ISSUE TITLE
Local jQuery for internet disconnected Netbox environments

### ISSUE THREAD

**Issue by tlskinneriv** [PieterL75/netbox_ipcalculator#15]
Propose to include a copy of jQuery in the repository added to the static files to ensure that this plugin will work in internet disconnected environments. The current import for jQuery pulls the code from `code.jquery.com` in template files [ipcalc.html](https://github.com/PieterL75/netbox_ipcalculator/blob/a6a8fb17f7670fbc87df1aa0abe7ac50b3dcd6ee/netbox_ipcalculator/templates/netbox_ipcalculator/core/ipcalc.html#L10) and [subnets.html](https://github.com/PieterL75/netbox_ipcalculator/blob/a6a8fb17f7670fbc87df1aa0abe7ac50b3dcd6ee/netbox_ipcalculator/templates/netbox_ipcalculator/core/subnets.html#L4). Another option would be to change the jQuery code to native JavaScript, eliminating the jQuery dependency, removing the import from the above-mentioned templates.

**Comment by PieterL75** [comment]
I released v1.4.5 with the local jQuery.
Nice idea ! thank you
