### ISSUE TITLE
Feature Request - Allow Calculation with subnet mask represented in octet

### ISSUE THREAD

**Issue by thefreakquency** [PieterL75/netbox_ipcalculator#3]
Thanks for your plugin! :)

I would like to see if it would be possible to allow both CIDR notation and full octet representation of subnet mask. 

In the input field, being able to type in 10.11.12.13/25 or 10.11.12.13/255.255.255.128 would be great.

**Comment by PieterL75** [comment]
Nice idea.. I  added it.. Let me know if it works as expected or not !
