### ISSUE TITLE
The number of ipv6 addresses is not displayed properly

### ISSUE THREAD

**Issue by Songxwn** [PieterL75/netbox_ipcalculator#8]
![image](https://github.com/PieterL75/netbox_ipcalculator/assets/21145071/f441513e-9c1e-42ba-9866-fe8129734d6f)

The number of ipv6 addresses is not displayed properly

**Comment by PieterL75** [comment]
That number is just soooo big..
I don't see the added value to display that very long number. This representation is the scientific notation of long numbers
